### PR TITLE
Fix test where key can be int.

### PR DESCRIPTION
**Pull request by VShkaberda**
Fix according to test explanation and how yaml handles key as int.

### CODE REVIEW

**Comment by oduvan** [comment]
no, use this link for testing

https://yaml-online-parser.appspot.com/

**Comment by VShkaberda** [comment]
The result you linked seems to be incorrect itself. Result returned as JSON differs from result returned as python. And python library `yaml` return integer key as string too. 
Screenshot_20220102_185508

**Comment by oduvan** [comment]
I see your point. 

But the mission description asks to validate tests with that tool. Where key is always a string. If we change it - it breaks all of the solutions

**Comment by VShkaberda** [comment]
It's your right to decide what to do here. I found it necessary to share information about this behavior.

**Comment by oduvan** [comment]
@VShkaberda I really appreciate it.

Thank you

**Comment by oduvan** [comment]
I was about to add it in the mission description, but we have it mentioned already: 

> The key can be any string consisting of Latin letters and numbers.

**Pull request closed without merging**
